### ISSUE TITLE
Lacking Diversity

### ISSUE THREAD

**Issue by OneTwistedTit** [masterzagh/DiscordBrowserTheme#1]
# I know you just opened this repo, but there seems to be a severe lack of Rust and Go codebases. Javascript is known to be a white supremacist dog whistle, but you aren't white. I expected more from you, sweetie.

# Could you also disable markdown composition in vector-im/element-web?

**Comment by masterzagh** [comment]
I am (not) sorry you feel this way. I hate rust and go (dilate, seethe, cope, rotate, gestate, germinate, accelerate).
I will go (pun intended) and write some more javascript so mald and cry about it.

> markdown

Sorry I don't know what that is. Is it a currency thing? I don't know, is that a currency thing?

Closed for anti-racism. We at masterzagh™ don't take your comments kindly and we strive for a anti-racism free environment.
